eigentest/apps/documents_analizer/urls.py
# -*- coding: utf-8 -*-
""" apps documents_analizer urls """

from django.urls import path

from . import views

app_name = 'documents_analizer'
urlpatterns = [
    path('', views.HashtagsView.as_view(), name='home'),
]

eigentest/eigentest/urls.py
# -*- coding: utf-8 -*-

""" 
eigentest urls

eigentest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('documents_analizer.urls', namespace="documents_analizer")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eigentest/apps/documents_analizer/models.py
# -*- coding: utf-8 -*-
""" apps documents_analizer models """

import os
from io import BytesIO

from django.db import models
from docx import Document as Docx

from utils.utils import highly_random_name, get_most_common_words


class Document(models.Model):
    """ Holds the document files """
    def update_filename(instance, filename):
        """ Changes the name of the file with a random name """
        path = os.path.join("documents_analizer", "documents")
        name = "{}{}".format(highly_random_name(),
                             os.path.splitext(filename)[1])
        return os.path.join(path, name)

    name = models.CharField(max_length=255)
    doc_file = models.FileField(upload_to=update_filename)

    class Meta:
        """ Meta class definitions """
        ordering = ['name']

    def __str__(self):
        """ Returns a string representation """
        return self.name

    def get_doc_file_extension(self):
        """ Returns the lowercase extension of the doc_file """
        return os.path.splitext(self.doc_file.name)[-1][1:].lower()

    def get_full_text_from_source(self):
        """ Returns the full text from the source """
        extension = self.get_doc_file_extension()

        if extension in ('txt', ''):
            # string = unicode(string)
            return self.doc_file.read().decode("utf-8")
        elif extension == 'docx':
            docx_document = Docx(BytesIO(self.doc_file.read()))
            return "\n".join(p.text for p in docx_document.paragraphs)
        elif extension == 'pdf':
            raise NotImplementedError()
        else:
            raise ValueError("file_format not supported")

    def get_lines_from_source(self):
        """ Returns a list with the lines from the source """
        extension = self.get_doc_file_extension()
        if extension in ('txt', ''):
            return tuple(line.decode('utf-8') for line in self.doc_file.readlines())
        elif extension == 'docx':
            docx_document = Docx(BytesIO(self.doc_file.read()))
            return tuple(paragrah.text for paragrah in docx_document.paragraphs)
        elif extension == 'pdf':
            raise NotImplementedError()
        else:
            raise ValueError("file_format not supported")

    def extract_hashtags(self):
        """
        Extracts the most common hashtags from the document and tries to add
        them to the Hashtag table.
        """
        most_common_words = get_most_common_words(
            self.get_full_text_from_source())
        queryset = Hashtag.objects.all()
        for word in most_common_words:
            tag = queryset.get_or_create(word=word.lower())[0]
            tag.documents.add(self)


class Hashtag(models.Model):
    """ Holds the hashtags and the related documents """
    word = models.CharField(max_length=60, unique=True)
    documents = models.ManyToManyField(Document)

    class Meta:
        """ Meta class definitions """
        ordering = ['word']

    def __str__(self):
        """ Returns a string representation """
        return self.word

eigentest/apps/utils/models.py
from django.db import models

# Create your models here.

eigentest/apps/documents_analizer/views.py
# -*- coding: utf-8 -*-
""" apps documents_analizer views """

from django.views.generic import ListView

from .models import Hashtag


class HashtagsView(ListView):
    """ Displays the hashtags list with their related documents """
    model = Hashtag
    template_name = 'documents_analizer/hastagsview.html'
    paginate_by = 5

eigentest/apps/utils/views.py
from django.shortcuts import render

# Create your views here.

eigentest/apps/documents_analizer/templates/documents_analizer/hastagsview.html
{% extends "base.html" %}
{% load bootstrap4 hashtag_tags %}

{% block body %}

  {% bootstrap_pagination page_obj %}

  <div class="table-responsive">
    <table class="table table-hover table-bordered">
      <thead class="thead-dark">
	<tr>
	  <th scope="col">Word(#)</th>
	  <th scope="col">Documents</th>
	  <th scope="col">Sentences containing the word</th>
	</tr>
      </thead>
      <tbody>
	{% for obj in object_list %}
	<tr>
          <th scope="row">{{ obj }}</th>
	  <td>{{ obj|print_related_docs|safe }}</td>
	  <td>{{ obj|print_sentences_with_hashtags|safe }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>

  {% bootstrap_pagination page_obj %}

{% endblock %}

eigentest/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<!-- saved from url=(0059)http://getbootstrap.com/docs/4.1/examples/starter-template/ -->
<html lang="en" class="gr__getbootstrap_com"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Eigen Technology Coding Test</title>

    {% bootstrap_css %}

  </head>

  <body data-gr-c-s-loaded="true">
    <main role="main" class="container">

      <div class="starter-template">
        <h1><a href="{% url 'documents_analizer:home' %}">Eigen Technology Coding Test</a></h1>
        {# <p class="lead"></p> #}

	{% block body %}{% endblock %}
	
      </div>

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
	 ================================================== -->
    {% bootstrap_javascript jquery='full' %}  

</body></html>